
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OrgChartWebApp.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario
{

    public int pk_Usuario { get; set; }

    public Nullable<int> fk_Directorio { get; set; }

    public string nombreUsuario { get; set; }

    public string emailUsuario { get; set; }

    public string loginUsuario { get; set; }

}

}
